# Generated by Django 4.0.3 on 2022-04-13 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Algoritmo',
            fields=[
                ('AlgoritmoId', models.AutoField(primary_key=True, serialize=False)),
                ('NombreAlgoritmo', models.CharField(max_length=500)),
                ('RutaAlgoritmo', models.CharField(max_length=500)),
                ('OrdenAlgoritmo', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Grafo',
            fields=[
                ('GrafoId', models.AutoField(primary_key=True, serialize=False)),
                ('NombreGrafo', models.CharField(max_length=500)),
            ],
        ),
    ]
