# Generated by Django 4.0.3 on 2022-04-19 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grafos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialEjecutciones',
            fields=[
                ('HistorialId', models.AutoField(primary_key=True, serialize=False)),
                ('GrafoId', models.IntegerField()),
                ('AlgoritmoId', models.IntegerField()),
                ('TiempoTeorico', models.IntegerField()),
                ('TiempoReal', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='grafo',
            name='Aciclico',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='grafo',
            name='Bipartito',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='grafo',
            name='Ciclico',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='grafo',
            name='Completo',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='grafo',
            name='Conexo',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='grafo',
            name='Dirigido',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='grafo',
            name='Multigrafo',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='grafo',
            name='Ponderado',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='grafo',
            name='links',
            field=models.JSONField(default=[]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='grafo',
            name='nodes',
            field=models.JSONField(default=[]),
            preserve_default=False,
        ),
    ]
