# Generated by Django 4.0.3 on 2022-04-28 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grafos', '0002_historialejecutciones_grafo_aciclico_grafo_bipartito_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialEjecuciones',
            fields=[
                ('HistorialId', models.AutoField(primary_key=True, serialize=False)),
                ('GrafoId', models.IntegerField()),
                ('AlgoritmoId', models.IntegerField()),
                ('Ecuacion', models.CharField(max_length=500)),
                ('TiempoTeorico', models.IntegerField()),
                ('TiempoReal', models.IntegerField()),
            ],
        ),
    ]
