# Generated by Django 4.0.3 on 2022-04-28 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grafos', '0003_historialejecuciones'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historialejecutciones',
            name='AlgoritmoId',
        ),
        migrations.RemoveField(
            model_name='historialejecutciones',
            name='GrafoId',
        ),
        migrations.RemoveField(
            model_name='historialejecutciones',
            name='TiempoReal',
        ),
        migrations.RemoveField(
            model_name='historialejecutciones',
            name='TiempoTeorico',
        ),
    ]
