# Generated by Django 4.0.3 on 2022-04-28 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grafos', '0004_remove_historialejecutciones_algoritmoid_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HistorialEjecutciones',
        ),
    ]
